export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export const CHANGE_USER_INFO = 'CHANGE_USER_INFO';
export const CHANGE_OFFLINE_STATUS = 'CHANGE_OFFLINE_STATUS';
export const CHANGE_SYNC_START = 'CHANGE_SYNC_START';

export const CHANGE_SELECT_PROJECT = 'CHANGE_SELECT_PROJECT';
export const CHANGE_PROJECT_PAYLOAD = 'CHANGE_PROJECT_PAYLOAD';
export const CHANGE_ACCESS_TOKEN = 'CHANGE_ACCESS_TOKEN';
export const MAP_FILTERS = 'MAP_FILTERS';
export const SEARCH_FILTERS = 'SEARCH_FILTERS';

export const SLIDE_STATUS = 'SLIDE STATUS';
export const SUB_SLIDE_STATUS = 'SUB_SLIDE_STATUS';
export const BACK_ICON_STATUS = 'BACK_ICON_STATUS';
export const CHANGE_PROFILE_STATUS = 'CHANGE_PROFILE_STATUS';
export const CHANGE_MORE_STATUS = 'CHANGE_MORE_STATUS';
export const SHOW_MORE_COMPONENT = 'SHOW_MORE_COMPONENT';
export const CHANGE_LIBRARY_CHILD_STATUS = 'CHANGE_LIBRARY_CHILD_STATUS';
export const CHANGE_CURRENT_LOCATION = 'CHANGE_CURRENT_LOCATION';
export const CHANGE_DISPOSITION_INFO = 'CHANGE_DISPOSITION_INFO';
export const CHANGE_LOCATION_ACTION = 'CHANGE_LOCATION_ACTION';
export const CHANGE_BOTTOM_TAB_ACTION = 'CHANGE_BOTTOM_TAB_ACTION';
export const LOCATION_CONFIRM_MODAL_VISIBLE = 'LOCATION_CONFIRM_MODAL_VISIBLE';
export const LOCATION_ID_CHANGED = 'LOCATION_ID_CHANGED';

// location action types
export const STATUS_PIN_KEY = 'STATUS_PIN_KEY';
export const CHANGE_PIN_KEY = 'CHANGE_PIN_KEY';
export const STATUS_LOCATION_MAP = 'STATUS_LOCATION_MAP';
export const CHANGE_LOCATION_MAP = 'CHANGE_LOCATION_MAP';
export const CHANGE_POLYGONS = 'CHANGE_POLYGONS';
export const STATUS_LOCATION_FILTERS = 'STATUS_LOCATION_FILTERS';
export const CHANGE_LOCATION_FILTERS = 'CHANGE_LOCATION_FILTERS';
export const STATUS_LOCATION_SEARCH_LISTS = 'STATUS_LOCATION_SEARCH_LISTS';
export const CHANGE_LOCATION_SEARCH_LISTS = 'CHANGE_LOCATION_SEARCH_LISTS';
export const STATUS_LOCATION_INFO = 'STATUS_LOCATION_INFO';
export const STATUS_DISPOSITION_FIELDS_UPDATE = 'STATUS_LOCATION_INFO_UPDATE';
export const LOCATION_LOOP_LISTS = 'LOCATION_LOOP_LISTS';

//pipeline action types
export const STATUS_PIPELINE_FILTERS = 'STATUS_PIPELINE_FILTERS';
export const CHANGE_PIPELINE_FILTERS = 'CHANGE_PIPELINE_FILTERS';
export const PIPELINE_SEARCH_FILTERS = 'PIPELINE_SEARCH_FILTERS';

// calendar action type

export const IS_CALENDAR_SELECTION = 'IS_CALENDAR_SELECTION';
export const SELECTED_LOCATIONS_FOR_CALENDAR =
  'SELECTED_LOCATIONS_FOR_CALENDAR';

// checkin and checkout status
export const CHECKIN = 'CHECKIN';
export const CHECKOUT = 'CHECKOUT';
export const LOCATION_CHECK_OUT_COMPULSORY = 'LOCATION_CHECK_OUT_COMPULSORY';
export const LOCATION_CHECK_OUT_COMPULSORY_DEVICE = 'LOCATION_CHECK_OUT_COMPULSORY_DEVICE';
export const LOCATION_CHECK_OUT_COMPULSORY_LOCATION_FIELD = 'LOCATION_CHECK_OUT_COMPULSORY_LOCATION_FIELD';

export const PRODUCT_PRICE_LISTS = 'PRODUCT_PRICE_LISTS';
export const SALES_SETTING = 'SALES_SETTING';
export const SALES_SETUP = 'SALES_SETUP';
export const SALES_SET_REGRET = 'SALES_SET_REGRET';
export const SET_CONTENT_FEED_DATA = 'SET_CONTENT_FEED_DATA';
export const SALES_SET_SEARCH_TEXT = 'SALES_SET_SEARCH_TEXT';
